environment: dev # dev is debug mode, expect dev, prod
name: "accounts" # Using dev environment, prod need to be injected at build
network: "tcp"
address: ":9091"
database:
  dsn: "postgres://root:root@127.0.0.1:5432/accounts?sslmode=disable"
  options:
    maxOpenConns: 1
    maxIdleConns: 2
    maxIdleTime: 30m
    maxLifetime: 1h

redis:
  address:
    - "127.0.0.1:6379"

etcd:
  endpoints:
    - ":2379"
#  autoSyncInterval: 1h
  dialTimeout: "20s"
#  dialKeepAliveTime: 2m
#  dialKeepAliveTimeout: 1m
#  maxCallSendSize: 100
#  maxCallRecvSize: 200
#  username: root
#  password: root
#  permWithoutStream: false
#  rejectOldCluster: false
#  rootCA: ""
#  pemKey: ""
#  pemCert: ""
