// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/transerver/commons/configs"
	"github.com/transerver/commons/gw"
	"github.com/transerver/commons/logger"
)

// Injectors from wire.go:

func wireApp() (*gw.Server, func(), error) {
	v := NewBootstrap()
	v2 := NewCfgOpts()
	iConfig, err := configs.Parse(v, v2...)
	if err != nil {
		return nil, nil, err
	}
	writer := NewLoggerWriter()
	zapLogger, cleanup := logger.NewLogger(iConfig, writer)
	v3 := NewGWOpts()
	server, err := gw.NewGatewayServer(zapLogger, iConfig, v3...)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return server, func() {
		cleanup()
	}, nil
}
