// Code generated by ent, DO NOT EDIT.

package rsa

const (
	// Label holds the string label denoting the rsa type in the database.
	Label = "rsa"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the rsa in the database.
	Table = "rsas"
)

// Columns holds all SQL columns for rsa fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
