// Code generated by ent, DO NOT EDIT.

package greeter

const (
	// Label holds the string label denoting the greeter type in the database.
	Label = "greeter"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the greeter in the database.
	Table = "greeters"
)

// Columns holds all SQL columns for greeter fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
