// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: accounts/pub.proto

package acctspb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RsaRequest with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RsaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RsaRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RsaRequestMultiError, or
// nil if none found.
func (m *RsaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RsaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if !_RsaRequest_Action_Pattern.MatchString(m.GetAction()) {
		err := RsaRequestValidationError{
			field:  "Action",
			reason: "value does not match regex pattern \"[A-Za-z]+\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_RsaRequest_Unique_Pattern.MatchString(m.GetUnique()) {
		err := RsaRequestValidationError{
			field:  "Unique",
			reason: "value does not match regex pattern \"[A-Za-z0-9_-]+\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for G

	if len(errors) > 0 {
		return RsaRequestMultiError(errors)
	}

	return nil
}

// RsaRequestMultiError is an error wrapping multiple validation errors
// returned by RsaRequest.ValidateAll() if the designated constraints aren't met.
type RsaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RsaRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RsaRequestMultiError) AllErrors() []error { return m }

// RsaRequestValidationError is the validation error returned by
// RsaRequest.Validate if the designated constraints aren't met.
type RsaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RsaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RsaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RsaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RsaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RsaRequestValidationError) ErrorName() string { return "RsaRequestValidationError" }

// Error satisfies the builtin error interface
func (e RsaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRsaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RsaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RsaRequestValidationError{}

var _RsaRequest_Action_Pattern = regexp.MustCompile("[A-Za-z]+")

var _RsaRequest_Unique_Pattern = regexp.MustCompile("[A-Za-z0-9_-]+")

// Validate checks the field values on RsaReplay with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RsaReplay) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RsaReplay with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RsaReplayMultiError, or nil
// if none found.
func (m *RsaReplay) ValidateAll() error {
	return m.validate(true)
}

func (m *RsaReplay) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Unique

	// no validation rules for Key

	if len(errors) > 0 {
		return RsaReplayMultiError(errors)
	}

	return nil
}

// RsaReplayMultiError is an error wrapping multiple validation errors returned
// by RsaReplay.ValidateAll() if the designated constraints aren't met.
type RsaReplayMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RsaReplayMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RsaReplayMultiError) AllErrors() []error { return m }

// RsaReplayValidationError is the validation error returned by
// RsaReplay.Validate if the designated constraints aren't met.
type RsaReplayValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RsaReplayValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RsaReplayValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RsaReplayValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RsaReplayValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RsaReplayValidationError) ErrorName() string { return "RsaReplayValidationError" }

// Error satisfies the builtin error interface
func (e RsaReplayValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRsaReplay.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RsaReplayValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RsaReplayValidationError{}
