// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: accounts/pub.proto

package acctspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RsaService_PublicKey_FullMethodName = "/org.github.transerver.accounts.RsaService/PublicKey"
	RsaService_Unique_FullMethodName    = "/org.github.transerver.accounts.RsaService/Unique"
)

// RsaServiceClient is the client API for RsaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RsaServiceClient interface {
	PublicKey(ctx context.Context, in *RsaRequest, opts ...grpc.CallOption) (*RsaReplay, error)
	Unique(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error)
}

type rsaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRsaServiceClient(cc grpc.ClientConnInterface) RsaServiceClient {
	return &rsaServiceClient{cc}
}

func (c *rsaServiceClient) PublicKey(ctx context.Context, in *RsaRequest, opts ...grpc.CallOption) (*RsaReplay, error) {
	out := new(RsaReplay)
	err := c.cc.Invoke(ctx, RsaService_PublicKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rsaServiceClient) Unique(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*wrapperspb.StringValue, error) {
	out := new(wrapperspb.StringValue)
	err := c.cc.Invoke(ctx, RsaService_Unique_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RsaServiceServer is the server API for RsaService service.
// All implementations must embed UnimplementedRsaServiceServer
// for forward compatibility
type RsaServiceServer interface {
	PublicKey(context.Context, *RsaRequest) (*RsaReplay, error)
	Unique(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error)
	mustEmbedUnimplementedRsaServiceServer()
}

// UnimplementedRsaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRsaServiceServer struct {
}

func (UnimplementedRsaServiceServer) PublicKey(context.Context, *RsaRequest) (*RsaReplay, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublicKey not implemented")
}
func (UnimplementedRsaServiceServer) Unique(context.Context, *emptypb.Empty) (*wrapperspb.StringValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unique not implemented")
}
func (UnimplementedRsaServiceServer) mustEmbedUnimplementedRsaServiceServer() {}

// UnsafeRsaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RsaServiceServer will
// result in compilation errors.
type UnsafeRsaServiceServer interface {
	mustEmbedUnimplementedRsaServiceServer()
}

func RegisterRsaServiceServer(s grpc.ServiceRegistrar, srv RsaServiceServer) {
	s.RegisterService(&RsaService_ServiceDesc, srv)
}

func _RsaService_PublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RsaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RsaServiceServer).PublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RsaService_PublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RsaServiceServer).PublicKey(ctx, req.(*RsaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RsaService_Unique_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RsaServiceServer).Unique(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RsaService_Unique_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RsaServiceServer).Unique(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// RsaService_ServiceDesc is the grpc.ServiceDesc for RsaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RsaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "org.github.transerver.accounts.RsaService",
	HandlerType: (*RsaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublicKey",
			Handler:    _RsaService_PublicKey_Handler,
		},
		{
			MethodName: "Unique",
			Handler:    _RsaService_Unique_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts/pub.proto",
}
