// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/transerver/pkg/types/enums"
)

type Account struct {
	ID       int64           `json:"id"`
	CreateAt time.Time       `json:"createAt"`
	UpdateAt sql.NullTime    `json:"updateAt"`
	UserID   string          `json:"userID"`
	Region   string          `json:"region"`
	Username string          `json:"username"`
	Area     string          `json:"area"`
	Phone    sql.NullString  `json:"phone"`
	Email    sql.NullString  `json:"email"`
	Avatar   sql.NullString  `json:"avatar"`
	Password []byte          `json:"password"`
	PwdLevel int16           `json:"pwdLevel"`
	Platform string          `json:"platform"`
	State    enums.UserState `json:"state"`
}

type Region struct {
	ID   int64           `json:"id"`
	Code string          `json:"code"`
	Area string          `json:"area"`
	Img  string          `json:"img"`
	Name json.RawMessage `json:"name"`
}
