// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/transerver/cli/templates/internal/ent/greeter"
)

// Greeter is the model entity for the Greeter schema.
type Greeter struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Greeter) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case greeter.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Greeter", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Greeter fields.
func (gr *Greeter) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case greeter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			gr.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Greeter.
// Note that you need to call Greeter.Unwrap() before calling this method if this Greeter
// was returned from a transaction, and the transaction was committed or rolled back.
func (gr *Greeter) Update() *GreeterUpdateOne {
	return (&GreeterClient{config: gr.config}).UpdateOne(gr)
}

// Unwrap unwraps the Greeter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gr *Greeter) Unwrap() *Greeter {
	_tx, ok := gr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Greeter is not a transactional entity")
	}
	gr.config.driver = _tx.drv
	return gr
}

// String implements the fmt.Stringer.
func (gr *Greeter) String() string {
	var builder strings.Builder
	builder.WriteString("Greeter(")
	builder.WriteString(fmt.Sprintf("id=%v", gr.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Greeters is a parsable slice of Greeter.
type Greeters []*Greeter

func (gr Greeters) config(cfg config) {
	for _i := range gr {
		gr[_i].config = cfg
	}
}
