// Code generated by ent, DO NOT EDIT.

package region

const (
	// Label holds the string label denoting the region type in the database.
	Label = "region"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldArea holds the string denoting the area field in the database.
	FieldArea = "area"
	// FieldImg holds the string denoting the img field in the database.
	FieldImg = "img"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the region in the database.
	Table = "regions"
)

// Columns holds all SQL columns for region fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldArea,
	FieldImg,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
